version: '3'
services:
  app:
    container_name: sejuta_cita_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: go.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./.env:/app/.env