apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejuta-cita-app
spec:
  replicas: 5
  selector:
    matchLabels:
      name: sejuta-cita-app
  template:
    metadata:
      labels:
        name: sejuta-cita-app
    spec:
      containers:
      - name: application
        image: emixbal/sejuta-cita:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
          - name: DB_DRIVER
            value: "mysql"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            value: "root"
          - name: DB_PORT
            value: "3306"
          - name: DB_HOST
            value: "127.0.0.1"
          - name: DB_NAME
            value: "sejuta-cita"
          - name: REDIS_DSN
            value: "127.0.0.1:6379"