apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejuta-cita-app
spec:
  replicas: 5
  selector:
    matchLabels:
      name: sejuta-cita-app
  template:
    metadata:
      labels:
        name: sejuta-cita-app
    spec:
      containers:
      - name: application
        image: emixbal/sejuta-cita:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
          - name: DB_DRIVER
            value: "mysql"
          - name: DB_USERNAME
            value: "sejutacita_api_user"
          - name: DB_PASSWORD
            value: "sejutacita_api123"
          - name: DB_PORT
            value: "3306"
          - name: DB_HOST
            value: "sejutacita-mysql"
          - name: DB_NAME
            value: "sejutacita_apidb"
          - name: REDIS_DSN
            value: "192.168.0.107:6379"
          - name: API_SECRET
            value: "98hbun98h"